# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ccd05ec93428db6f48297273a0bbd81f8a972e4695deaa4e80830cff77e31f3119b7e0c8d65f68a4944e871b0e44265a45e2073c0c1c67d108bb9d4b6e81d114

test:
  secret_key_base: c62575b9ce00ea8365a39701a0a530ab066c0ce6918a5592b355b2a0ee966004388fd08c48f630f1e359a1a9804267e90fdfc47105a3f7460bbdde8f53a293d6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
